### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by franzliedke** [julik/idempo#11]
Dear @julik, your excellent article on the genesis of idempo brought me here, and I was impressed by the engineering that went into this, and into its explanation as well.

That article, and the relatively small amount of code gives me confidence about using the project, but on the other hand it's not very widely known and hasn't seen any updates in a while. Since you wrote you no longer work at WeTransfer, I wanted to make sure this gem is still maintained, before I use it at my workplace.

Again, considering the size of the problem and the codebase, I would assume it can be considered complete. What kept you from releasing a 1.0 to "officially" mark it as stable then? 😊 

Props for open-sourcing this and greetings from Germany! 👋🏼

**Comment by julik** [comment]
Good question - I never actually got to releasing a 1.0. It is feature complete and has been in production use for a couple of years now. The only change that is likely to happen is an advisory-lock-less strategy so that idempo can be used with pgbouncer.

For all intents and purposes you may consider idempo stable and production-ready

**Comment by franzliedke** [comment]
That's great to hear, thanks so much!

(P.S.: Let's tag a 1.0 then. 🎉)
